- Media:
    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.host.or.ip
        widget:
            type: sonarr
            fields: ["wanted", "queued"]
            url: http://sonarr.host.or.ip
            key: apikeyapikeyapikeyapikeyapikey

- Group A:
    - Service A:
        href: http://localhost/
        description: This is my service
        server: my-server
        container: cloudflared
    - Service B:
        href: http://localhost/
        description: This is my service
        server: my-server
        container: homepage